default_black_list = [
    "nigga",
    "bitch",
    "negga",
    "fuck you",
    "son of a bitch",
    "whore",
    "fuck u",
    "bastard",
    "arse",
    "asshole",
    "bitch",
    "bollocks",
    "bugger",
    "child-fucker",
    "cunt",
    "effing",
    "frigger",
    "fuck",
    "horseshit",
    "jesus wept",
    "motherfucker",
    "prick",
    "shitass",
    "shit ass",
    "slut",
    "son of a whore",
    "twat",
    "nigger",
    "negger",
    "nibber",
    "nibba",
    "n i g g a",
    "n e g g a",
    "n i g g e r",
    "n e g g e r",
    "n i b b a",
    "n i b b e r"
]